---
# tasks file for kubernetes

- name: Make sure that the br_netfilter module is loaded
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: ensure net.bridge.bridge-nf-call-iptables is set to 1 in your sysctl config
  ansible.builtin.template:
    src: files/modules-load.d/k8s.conf
    dest: /etc/modules-load.d/k8s.conf

- name: ensure net.bridge.bridge-nf-call-iptables is set to 1 in your sysctl config
  ansible.builtin.template:
    src: files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Make sure that dns server are correctly configure
  ansible.builtin.template:
    src: files/resolv.conf
    dest: /etc/resolv.conf

- name: Download the Google Cloud public signing key (Kubernetes)
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add the Kubernetes apt repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: true

- name: install kubelet, kubeadm and kubectl
  apt:
    pkg:
    - kubelet=1.23.6-00
    - kubeadm=1.23.6-00
    - kubectl=1.23.6-00
    update_cache: yes
    force: yes

- name: prevent kubelet from being upgraded
  dpkg_selections:
    name: kubelet
    selection: hold

- name: prevent kubeadm from being upgraded
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: prevent kubectl from being upgraded
  dpkg_selections:
    name: kubectl
    selection: hold

- name: change docker cgroup driver to systemd 
  ansible.builtin.template:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - Restart service docker, in all cases, also issue daemon-reload to pick up config changes

- name: disable swapp memory
  command: swapoff -a

# # solve issue with kubernetes=v1.24
# - name: delete /etc/containerd/config.toml
#   file:
#     path: /etc/containerd/config.toml
#     state: absent
#   notify: 
#   - Restart service containerd

# # solve issue with kubernetes=v1.24
# - name: Restart service containerd
#   ansible.builtin.systemd:
#     state: restarted
#     name: containerd

- name: reset kubeadm (make sure to reset kube conf in all host if a config already exist to avoid issue config already exist when trying to init master node or join a cluster)
  command: kubeadm reset -f
  ignore_errors: true
