---
# tasks file for helm
- name: Add Helm's official GPG key
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add repo package for Helm
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    update_cache: true
    
- name: install helm
  apt:
    name: helm
    update_cache: yes

# - name: Download foo.conf
#   get_url:
#     url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
#     dest: /tmp/get_helm.sh
#     mode: '700'
    
# - name: install helm
#   shell: ./get_helm.sh
#   args:
#     chdir: /tmp/
