---
- name: Install and configure Kubernetes Master Node
  hosts: master
  gather_facts: yes
  become: yes
  roles:
  - common
  - docker
  - kubernetes
  - helm
  - runner
  - master

- name: Apply deployment dashboard-adminuser, Dashboard, Namespaces
  hosts: master
  gather_facts: no
  roles: 
  - deployment
  - prometheus