---
- name: Install and configure Kubernetes Master Node
  hosts: master
  gather_facts: yes
  become: yes
  roles:
  - master

- name: add Workers node to the cluster
  hosts: worker
  gather_facts: no
  become: yes
  roles: 
  - worker

- name: Apply deployment dashboard-adminuser, Dashboard, Namespaces
  hosts: master
  gather_facts: no
  roles: 
  - deployment
  - prometheus
