apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: iris-ws
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-enterprise-kafka:7.0.0
        ports:
        - containerPort: 9092
        - containerPort: 29092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:32181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "false"
        - name: KAFKA_METRIC_REPORTERS
          value: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
        - name: CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS
          value: "localhost:29092"
        - name: CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT
          value: "zookeeper-service:32181"
        - name: CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS
          value: "1"
        - name: CONFLUENT_METRICS_ENABLE
          value: "true"
        - name: CONFLUENT_SUPPORT_CUSTOMER_ID
          value: "anonymous"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: iris-ws
spec:
  ports:
    - protocol: "TCP"
      port: 29092       
      targetPort: 29092
  type: LoadBalancer  
  selector:
    app: kafka