apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  namespace: iris-ws
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.0.0
        ports:
        - containerPort: 32181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "32181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: iris-ws
spec:
  ports:
    - protocol: "TCP"
      port: 32181 
      targetPort: 32181 
  selector:
    app: zookeeper